### ISSUE TITLE
Remodel car

### ISSUE THREAD

**Issue by Druner** [DIT113-V22/group-02#15]
As a driver, I want the car in the emulator to be remodeled, so that it more closely aligns with normal car dimensions and therfore has a maneuverability more similar to normal cars
Acceptance Criteria:
- [x] The new car model can be compiled in the SMCE emulator
- [x] The new cars dimensions are twice as long as it is wide

**Comment by platisd** [comment]
Please change the name of the issue to something more brief. You also would be probably better of if you use GitHub's numbering (i.e. `#15` for this story).

**Comment by Druner** [comment]
Since Issues can't be removed, renamed this unused Issue that was closed instead of creating a new one

**Comment by Druner** [comment]
Not supposed to close yet, Pull request connected to this Issue is only the start of the work for the Issue, not the end

**Comment by platisd** [comment]
You should also add a label `invalid`  to make this clearer (in that case you don't need to comment further)

**Comment by adityak714** [comment]
The acceptance criteria have also been met for this. The car compiles, and incl. the chassis length, front hood length, and tail-light protruding, the length is double of that of the car's width.
