### ISSUE TITLE
Add home screen in the application

### ISSUE THREAD

**Issue by arrestoteles** [DIT113-V22/group-02#31]
As a user, I want to be able to open up the application on my mobile phone so that I can see what functionalities are available

Acceptance criteria:

**Comment by Druner** [comment]
before closing this better acceptance criteria needs to be written

**Comment by arrestoteles** [comment]
@Druner correct. But after our discussion today we'll just start with the navigation screen and delete the home screen because it serves no purpose for our customers. If needed we can add it back to the pipeline.

**Comment by arrestoteles** [comment]
@Druner wrote acceptance criteria just in case.
