### ISSUE TITLE
Creation of the terrain

### ISSUE THREAD

**Issue by adityak714** [DIT113-V22/group-02#4]
As a car driver, I want to be able to manoeuvre the car in a virtual environment of a parking lot so that i can test the functionality of autonomous parking.

Acceptance Criteria:

- [x] Should be able to load in the smartcar into the new SMCE terrain
- [x] Terrain has 6 to 8 parking lots.
- [x] Terrain has at least three DomyCars.

**Comment by arrestoteles** [comment]
@adityak714 is this done or should we move into sprint2?

**Comment by adityak714** [comment]
The acceptance criteria are met for this beginning issue of the creation of the terrain. More extended requirements could also follow later, like in issue #49, where the plan is to make a few more additions in the terrain to allow, potentially, more types of parking in the system.
