### ISSUE TITLE
Control car with a joystick

### ISSUE THREAD

**Issue by sh4r10** [DIT113-V22/group-02#59]
As a user, I want to be able to control the car using a joystick through the android application. 
Acceptance criteria
- [x] User should be able to move the car forward, backward, right and left with the joystick. 
- [x] The angle of the car should be consistent with the angle of the joystick

**Comment by arrestoteles** [comment]
@sh4r10 removed from this issues to work in issue #69. @arrestoteles added to work with @um33 on joystick.
