### ISSUE TITLE
Implement smartcar front camera view on mobile app

### ISSUE THREAD

**Issue by arrestoteles** [DIT113-V22/group-02#67]
As a user, I want to get a view of my car from the front so that I am able to see where the car is heading, especially while initiating a parking by going forward. 

Acceptance criteria
- [x] The hood of the car, and both corners of the hood, with obstacles in close proximity visible to be detected through the cam feed.

**Comment by arrestoteles** [comment]
@adityak714 @Gabri1998 just a reminder that user story and acceptance criteria is missing.

**Comment by Gabri1998** [comment]
The camera now is streaming the the front view of the car properly even during auto parking.
