### ISSUE TITLE
Basic mapping and drive foward

### ISSUE THREAD

**Issue by Druner** [DIT113-V22/group-02#69]
As a driver, I want the car to be able to drive forward using an internal map of the parking lot, so that I don't have to find a parking spot and do the driving myself

acceptance criteria:
- [x] The car needs an internal map that mapps the parking lot
- [x] The car should be able to assign itself to a empty parking spot using the map
- [x] The car should be able to drive towards the assigned parking spot

**Comment by arrestoteles** [comment]
@Druner just a reminder that user story and acceptance criteria is missing.
