### ISSUE TITLE
Modify checkObstacles 

### ISSUE THREAD

**Issue by sh4r10** [DIT113-V22/group-02#77]
Modify the checkObstacles method to include the new sensor methods.
Acceptance Criteria:
- [ ] The car does not collide with any solid object throughout all forms of driving
- [ ] The car makes appropriate manoeuvres necessary to avoid collisions.

**Comment by Druner** [comment]
this is very similar to #45, we don't need them both right?

**Comment by Druner** [comment]
to similar to #45, removing it
