### ISSUE TITLE
Finalize README.md & Demo video

### ISSUE THREAD

**Issue by sh4r10** [DIT113-V22/group-02#88]
Ensure your project has a high quality README.md file which contains (but not limited to) the following:

Explains "What? Why? How?" about the project
Illustrates the hardware and software architecture with text and/or diagrams
Instructs how to set up and get started with the project
Includes a link to a Youtube video with a demo of the full functionality of your project
No length limit
Should showcase the entire functionality of the product
Should explain the problem your system solves and its business potential
Include any other technical or otherwise details that you see fit
Provide a link to your README.md file.

Some ideas on how to improve your README.md aside of the above:

Write a user manual
Write a "Get started" guide for developers

- [x] Add instructions for running our program, along with the dependencies into the README.md file
- [x] Add demo video to the readme file
- [x] Add a user manual

**Comment by arrestoteles** [comment]
@sh4r10 good that you've added this bhai! 💯

**Comment by arrestoteles** [comment]
Christopher Nolan called and would like that we start shooting the video on May 25th! 🎥
