### ISSUE TITLE
Finalize feature specification 

### ISSUE THREAD

**Issue by sh4r10** [DIT113-V22/group-02#93]
Finalize the wiki pages containing the features specification and the corresponding requirements.

Provide a link to your milestones and make sure that all of them contain links to your features on the wiki.

Some ideas on how to improve existing requirements documentation and overall process structure:

Make sure that all stories (GitHub issues) are linked to Milestones and it is clear which commit(s) solve them
Enrich requirements with more details, examples and usage scenarios

- [x] Make sure that the user stories are up to date
- [x] Link all user stories to issues, if there is no link, provide an explanation
- [x] Add small demo videos where possible

**Comment by arrestoteles** [comment]
@Druner good work with this issue! 💯 ✅

**Comment by arrestoteles** [comment]
Closing issue.
